export const GET_OVERVIEW_REQUEST = 'GET_OVERVIEW_REQUEST';
export const GET_OVERVIEW_SUCCESS = 'GET_OVERVIEW_SUCCESS';
export const GET_OVERVIEW_FAIL = 'GET_OVERVIEW_FAIL';

export const GET_CAMPAIGN_REQUEST = 'GET_CAMPAIGN_REQUEST';
export const GET_CAMPAIGN_SUCCESS = 'GET_CAMPAIGN_SUCCESS';
export const GET_CAMPAIGN_FAIL = 'GET_CAMPAIGN_FAIL';
